### ISSUE TITLE
Inquiry about Data preprocessing

### ISSUE THREAD

**Issue by shwan333** [WindyLee0822/TREA#5]
Hello, @WindyLee0822 

I'm reading your paper and code, the paper looks valuable in the field of Conversational Recommendation, thanks for the great work :)

I examine your code and find that the raw data in your repository is  different from the official data in RecDial official data. I've looked through all the codes, but couldn't find the preprocessing code. 

Could you please let me know where appropriate preprocessing code is or provide guidance on how to pre-process the RecDial official data to be your raw data?

Any help would be appreciated!

Regards,
Choi

**Comment by WindyLee0822** [comment]
Hi, Choi. 

These two files "train.json" and "test.json" are raw files from this paper "CR-Walker: Tree-Structured Graph Reasoning and Dialog Acts for
Conversational Recommendation" (git link:  https://github.com/truthless11/CR-Walker). If you want to obtain the data files we finally use, i.e. "train_publish.json" and  "test_publish.json", you just need to set process_raw_data=True during the dataset initialization.

If you have any question, feel free to contact me.

Regards,
Wendi

**Comment by shwan333** [comment]
Thank you very much. Your answer helps me to clarify the pre-processing step of RecDial dataset. I truly appreciate the time and effort you've dedicated to this repository.
